import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Navigation from './components/navigation/Navbart';
import StoreProvider from './StoreProvider';
import Popup from './components/Layouts/Popup/Popup';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
      <html lang="en">
        <body className={inter.className}>
          <div id="root">
            <div id="popup"></div>
            <div id="overlay"></div>
            <Popup />
            <Navigation />
            {children}
          </div>
        </body>
      </html>
    </StoreProvider>
  );
}
